### ISSUE TITLE
how to flash?

### ISSUE THREAD

**Issue by itzik16** [hamityanik/ULP-Weather-Logger#1]
Hey mate Ive bought the board from tindie and having trouble to upload the firmware onto it
I've downloaded the additional included github libraries and blynk libraries and added ESP8266 boards  to the IDE using that link  

> http://arduino.esp8266.com/versions/2.3.0/package_esp8266com_index.json

I have chose the ESP866 generic board with all the defualt setting and fail to flash I also uncommented the debug line and still nothing seem to happen. Can you please help, and show me your configuration and how to configure it properly.
It compiles but doesn't flash.
I used 3 different UART to USB just to make sure it wasnt the issue
Please help, Thanks In advance.

**Comment by hamityanik** [comment]
Hello,

Did you read "How to program?" section on product description on Tindie?

https://www.tindie.com/products/iohippo/ulp-weather-logger-with-esp8266-wifi-iot/

Make sure your UART connection, GND to GND, TX to RX, RX to TX, and also USBtoUART bridge logic levels. It must be 3.3v.

Then, to enter bootload mode:
Press FLASH button and without releasing it, press and release ONE SHOT button, PWR LED will lights up. Release FLASH button. At this state, you are able to upload your sketch.

Arduino IDE configuration:
![](https://raw.githubusercontent.com/hamityanik/ULP-Weather-Logger/master/Images/arduino_config.png)

**Comment by larskotthoff** [comment]
I'm trying with exactly these settings from the Arduino IDE, but no luck. When I hold flash and press and release one shot, pwr and d1 leds light up. I'm getting this error message in the Arduino IDE:

    warning: espcomm_sync failed
    error: espcomm_open failed
    error: espcomm_upload_mem failed
    error: espcomm_upload_mem failed

I have no problem uploading sketches to other arduinos.

**Comment by hamityanik** [comment]
Which USB to UART adapter you are using?

**Comment by larskotthoff** [comment]
This one: https://www.amazon.com/gp/product/B01LRVQIFQ/

**Comment by hamityanik** [comment]
Would you share Arduino IDE's tools menu screenshot?

**Comment by larskotthoff** [comment]
Sure, attached. The port is /dev/ttyUSB0, I didn't attach the adapter so it doesn't show up.

![settings](https://user-images.githubusercontent.com/579233/39400631-5a6a8292-4af1-11e8-9e37-c22b9c7b7983.png)

**Comment by hamityanik** [comment]
If device is ON, you can enter bootload mode by:
Press and hold Flash button, press and release Reset button, release Flash button. 

If device is OFF:
Press and hold Flash button, press and release ONE SHOT button, release Flash button. 

Then try uploading your sketch with these settings.

**Comment by larskotthoff** [comment]
Thanks, I finally got it to work. I had connected RX to RX and TX to TX, but it turns out that it wanted RX connected to TX and TX to RX (maybe something mislabeled?). Working now.

**Comment by hamityanik** [comment]
Good to hear that. :)
